import { Patient } from '@/types';

export const samplePatients: Patient[] = [
  {
    id: 'PT-001', name: 'James Harrison', age: 67, gender: 'male',
    symptoms: ['Chest Pain', 'Difficulty Breathing', 'Dizziness'], painLevel: 9,
    heartRate: 132, bloodPressure: '185/110', oxygenLevel: 88, temperature: 37.2,
    medicalHistory: 'Previous cardiac arrest, diabetes type 2',
    emergencyNotes: 'Patient clutching chest, diaphoretic',
    arrivalTime: new Date(Date.now() - 8 * 60000), urgencyScore: 94,
    priority: 'critical', status: 'in-treatment', assignedArea: 'Immediate Treatment Room',
    riskFactors: [
      { text: 'Critical SpO2 (88%)', severity: 'high' },
      { text: 'Tachycardia (HR: 132 bpm)', severity: 'high' },
      { text: 'Hypertensive crisis (BP: 185/110)', severity: 'high' },
      { text: 'Critical combo: chest pain + dyspnea', severity: 'high' },
    ],
    aiExplanation: 'Patient classified as CRITICAL priority with urgency score 94/100. Presenting symptoms: Chest Pain, Difficulty Breathing, Dizziness. Key risk factors: Critical SpO2, tachycardia, hypertensive crisis.',
  },
  {
    id: 'PT-002', name: 'Sarah Mitchell', age: 34, gender: 'female',
    symptoms: ['Severe Allergic Reaction', 'Difficulty Breathing'], painLevel: 7,
    heartRate: 118, bloodPressure: '95/60', oxygenLevel: 91, temperature: 37.8,
    medicalHistory: 'Known shellfish allergy',
    emergencyNotes: 'Facial swelling, hives, epinephrine administered en route',
    arrivalTime: new Date(Date.now() - 15 * 60000), urgencyScore: 82,
    priority: 'critical', status: 'in-treatment', assignedArea: 'Immediate Treatment Room',
    riskFactors: [
      { text: 'Low SpO2 (91%)', severity: 'medium' },
      { text: 'Elevated heart rate (HR: 118 bpm)', severity: 'medium' },
      { text: 'Severe pain level (7/10)', severity: 'high' },
    ],
    aiExplanation: 'Anaphylactic reaction with breathing difficulty. Immediate airway monitoring required.',
  },
  {
    id: 'PT-003', name: 'Robert Chen', age: 52, gender: 'male',
    symptoms: ['Abdominal Pain', 'Nausea/Vomiting', 'High Fever'], painLevel: 6,
    heartRate: 96, bloodPressure: '138/88', oxygenLevel: 97, temperature: 39.1,
    medicalHistory: 'Appendectomy 2019',
    emergencyNotes: 'Pain in right lower quadrant',
    arrivalTime: new Date(Date.now() - 32 * 60000), urgencyScore: 58,
    priority: 'high', status: 'waiting', assignedArea: 'Urgent Care Queue',
    riskFactors: [
      { text: 'High fever (39.1°C)', severity: 'high' },
      { text: 'Moderate pain level (6/10)', severity: 'medium' },
    ],
    aiExplanation: 'Abdominal pain with fever suggests possible appendicitis. Surgical consultation recommended.',
  },
  {
    id: 'PT-004', name: 'Emily Watson', age: 28, gender: 'female',
    symptoms: ['Head Injury', 'Dizziness', 'Nausea/Vomiting'], painLevel: 7,
    heartRate: 88, bloodPressure: '122/78', oxygenLevel: 98, temperature: 36.9,
    medicalHistory: 'None',
    emergencyNotes: 'Fall from bicycle, helmet worn, brief LOC reported',
    arrivalTime: new Date(Date.now() - 22 * 60000), urgencyScore: 55,
    priority: 'high', status: 'waiting', assignedArea: 'Urgent Care Queue',
    riskFactors: [
      { text: 'Severe pain level (7/10)', severity: 'high' },
      { text: 'Head trauma with LOC', severity: 'high' },
    ],
    aiExplanation: 'Head injury with LOC requires CT evaluation. Neurological monitoring indicated.',
  },
  {
    id: 'PT-005', name: 'Michael Torres', age: 45, gender: 'male',
    symptoms: ['Back Pain', 'Joint Pain'], painLevel: 5,
    heartRate: 78, bloodPressure: '128/82', oxygenLevel: 99, temperature: 36.8,
    medicalHistory: 'Chronic back pain, disc herniation L4-L5',
    emergencyNotes: 'Exacerbation after lifting heavy objects',
    arrivalTime: new Date(Date.now() - 45 * 60000), urgencyScore: 28,
    priority: 'medium', status: 'waiting', assignedArea: 'Standard Care Queue',
    riskFactors: [{ text: 'Moderate pain level (5/10)', severity: 'medium' }],
    aiExplanation: 'Chronic back pain exacerbation. Standard care with pain management appropriate.',
  },
  {
    id: 'PT-006', name: 'Lisa Park', age: 8, gender: 'female',
    symptoms: ['High Fever', 'Cough', 'Sore Throat'], painLevel: 3,
    heartRate: 110, bloodPressure: '100/65', oxygenLevel: 97, temperature: 38.9,
    medicalHistory: 'Asthma',
    emergencyNotes: '3-day persistent fever, OTC meds not helping',
    arrivalTime: new Date(Date.now() - 55 * 60000), urgencyScore: 38,
    priority: 'medium', status: 'waiting', assignedArea: 'Standard Care Queue',
    riskFactors: [
      { text: 'Pre-existing respiratory condition', severity: 'medium' },
      { text: 'Elevated temperature (38.9°C)', severity: 'medium' },
    ],
    aiExplanation: 'Pediatric patient with persistent fever. Pre-existing asthma noted. Respiratory assessment recommended.',
  },
  {
    id: 'PT-007', name: 'David Kim', age: 22, gender: 'male',
    symptoms: ['Minor Cut/Wound'], painLevel: 2,
    heartRate: 72, bloodPressure: '118/75', oxygenLevel: 99, temperature: 36.6,
    medicalHistory: 'None',
    emergencyNotes: 'Laceration to left forearm, controlled bleeding',
    arrivalTime: new Date(Date.now() - 70 * 60000), urgencyScore: 12,
    priority: 'low', status: 'waiting', assignedArea: 'Waiting Room',
    riskFactors: [],
    aiExplanation: 'Minor laceration with stable vitals. Standard wound care applies.',
  },
];
